import 'dart:io';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:file_picker/file_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'note_service.dart';
import '../models/note.dart';

class PdfUploadService {
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final NoteService _noteService = NoteService();
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // Pick and upload PDF file
  Future<String?> pickAndUploadPdf({
    required String title,
    required String subjectId,
    required String semesterId,
    List<String> tags = const [],
    bool isPublic = false,
  }) async {
    try {
      // Pick PDF file
      FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf'],
      );

      if (result == null || result.files.single.path == null) {
        return null; // User cancelled
      }

      File pdfFile = File(result.files.single.path!);
      String fileName = result.files.single.name;
      
      // Upload to Firebase Storage
      String downloadUrl = await uploadPdfToStorage(
        pdfFile: pdfFile,
        fileName: fileName,
      );

      // Create note with PDF link
      await createNoteWithPdf(
        title: title,
        pdfUrl: downloadUrl,
        fileName: fileName,
        subjectId: subjectId,
        semesterId: semesterId,
        tags: tags,
        isPublic: isPublic,
      );

      return downloadUrl;
    } catch (e) {
      throw Exception('Failed to upload PDF: $e');
    }
  }

  // Upload PDF to Firebase Storage
  Future<String> uploadPdfToStorage({
    required File pdfFile,
    required String fileName,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      print('🔥 Uploading PDF: $fileName');
      print('👤 User: ${user.email}');
      print('📦 Storage bucket: ${_storage.ref().bucket}');

      // Create unique file name
      String uniqueFileName = '${user.uid}_${DateTime.now().millisecondsSinceEpoch}_$fileName';
      
      // Create storage reference
      Reference ref = _storage
          .ref()
          .child('pdfs')
          .child(user.uid)
          .child(uniqueFileName);

      print('📁 Storage path: ${ref.fullPath}');

      // Upload file with metadata
      SettableMetadata metadata = SettableMetadata(
        contentType: 'application/pdf',
        customMetadata: {
          'uploadedBy': user.uid,
          'originalName': fileName,
        },
      );

      UploadTask uploadTask = ref.putFile(pdfFile, metadata);
      
      // Monitor upload progress
      uploadTask.snapshotEvents.listen((TaskSnapshot snapshot) {
        double progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        print('📊 Upload progress: ${progress.toStringAsFixed(1)}%');
      });
      
      // Wait for upload completion
      TaskSnapshot snapshot = await uploadTask;
      
      print('✅ Upload completed, getting download URL...');
      
      // Get download URL
      String downloadUrl = await snapshot.ref.getDownloadURL();
      
      print('🔗 Download URL: $downloadUrl');
      
      return downloadUrl;
    } catch (e) {
      print('❌ Storage upload error: $e');
      throw Exception('Failed to upload PDF to storage: $e');
    }
  }

  // Create note with PDF attachment
  Future<void> createNoteWithPdf({
    required String title,
    required String pdfUrl,
    required String fileName,
    required String subjectId,
    required String semesterId,
    List<String> tags = const [],
    bool isPublic = false,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      Note note = Note(
        id: '', // Will be generated by Firestore
        title: title,
        content: '📄 PDF Attachment: $fileName\n\nDownload link: $pdfUrl',
        subjectId: subjectId,
        semesterId: semesterId,
        userId: user.uid,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        tags: ['PDF', ...tags],
        isPublic: isPublic,
        likes: 0,
        likedBy: [],
      );

      await _noteService.createNote(note);
    } catch (e) {
      throw Exception('Failed to create note with PDF: $e');
    }
  }

  // Delete PDF from storage
  Future<void> deletePdf(String downloadUrl) async {
    try {
      Reference ref = _storage.refFromURL(downloadUrl);
      await ref.delete();
    } catch (e) {
      throw Exception('Failed to delete PDF: $e');
    }
  }

  // Get user's uploaded PDFs
  Future<List<Map<String, dynamic>>> getUserPdfs() async {
    try {
      final user = _auth.currentUser;
      if (user == null) throw Exception('User not authenticated');

      // Get user's notes with PDF tags
      List<Note> userNotes = await _noteService.getUserNotes(user.uid);
      
      // Filter notes with PDF attachments
      List<Map<String, dynamic>> pdfNotes = userNotes
          .where((note) => note.tags.contains('PDF'))
          .map((note) => {
                'noteId': note.id,
                'title': note.title,
                'content': note.content,
                'fileName': _extractFileName(note.content),
                'pdfUrl': _extractPdfUrl(note.content),
                'createdAt': note.createdAt,
                'subjectId': note.subjectId,
                'semesterId': note.semesterId,
                'tags': note.tags,
                'likes': note.likes,
              })
          .toList();

      return pdfNotes;
    } catch (e) {
      throw Exception('Failed to get user PDFs: $e');
    }
  }

  // Extract file name from note content
  String _extractFileName(String content) {
    final lines = content.split('\n');
    for (String line in lines) {
      if (line.startsWith('📄 PDF Attachment:')) {
        return line.replaceFirst('📄 PDF Attachment: ', '');
      }
    }
    return 'Unknown File';
  }

  // Extract PDF URL from note content
  String _extractPdfUrl(String content) {
    final lines = content.split('\n');
    for (String line in lines) {
      if (line.startsWith('Download link:')) {
        return line.replaceFirst('Download link: ', '');
      }
    }
    return '';
  }
}
