// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApgqjZzDA2h8rwEA70k4VOQF67wcFWMlA',
    appId: '1:126611795344:web:5c96b5a91b114c63b09715',
    messagingSenderId: '126611795344',
    projectId: 'winggle-40155',
    authDomain: 'winggle-40155.firebaseapp.com',
    storageBucket: 'winggle-40155.firebasestorage.app',
    measurementId: 'G-B6X0063P5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmQnEgTzzAtDGZkCI855lE7TZoGcdtL0',
    appId: '1:126611795344:android:1ee292235fe1ee96b09715',
    messagingSenderId: '126611795344',
    projectId: 'winggle-40155',
    storageBucket: 'winggle-40155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTc68zGqT83KRiBh9RUbWzqipFj-_D03k',
    appId: '1:126611795344:ios:c4ef83b7e839441fb09715',
    messagingSenderId: '126611795344',
    projectId: 'winggle-40155',
    storageBucket: 'winggle-40155.firebasestorage.app',
    iosBundleId: 'com.example.winggle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTc68zGqT83KRiBh9RUbWzqipFj-_D03k',
    appId: '1:126611795344:ios:c4ef83b7e839441fb09715',
    messagingSenderId: '126611795344',
    projectId: 'winggle-40155',
    storageBucket: 'winggle-40155.firebasestorage.app',
    iosBundleId: 'com.example.winggle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApgqjZzDA2h8rwEA70k4VOQF67wcFWMlA',
    appId: '1:126611795344:web:a1672bd27ee29c9db09715',
    messagingSenderId: '126611795344',
    projectId: 'winggle-40155',
    authDomain: 'winggle-40155.firebaseapp.com',
    storageBucket: 'winggle-40155.firebasestorage.app',
    measurementId: 'G-4C0L3WKY9W',
  );
}
