// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30jqcEXRk-jQE5qylvc5i0o6Ion8w1-I',
    appId: '1:521484955833:web:ff2632d589aa3156a56b68',
    messagingSenderId: '521484955833',
    projectId: 'winggle-ac8d7',
    authDomain: 'winggle-ac8d7.firebaseapp.com',
    storageBucket: 'winggle-ac8d7.firebasestorage.app',
    measurementId: 'G-58304C66NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_mIlXbSxxrKGealQIIt0skSVVAYQpQ6o',
    appId: '1:521484955833:android:7859fe4680a91e40a56b68',
    messagingSenderId: '521484955833',
    projectId: 'winggle-ac8d7',
    storageBucket: 'winggle-ac8d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryj-6UPWqeKuUd1zPN0iqwflPDEGn0UE',
    appId: '1:521484955833:ios:b1f8a694dfce9e27a56b68',
    messagingSenderId: '521484955833',
    projectId: 'winggle-ac8d7',
    storageBucket: 'winggle-ac8d7.firebasestorage.app',
    iosBundleId: 'com.example.winggle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryj-6UPWqeKuUd1zPN0iqwflPDEGn0UE',
    appId: '1:521484955833:ios:b1f8a694dfce9e27a56b68',
    messagingSenderId: '521484955833',
    projectId: 'winggle-ac8d7',
    storageBucket: 'winggle-ac8d7.firebasestorage.app',
    iosBundleId: 'com.example.winggle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD30jqcEXRk-jQE5qylvc5i0o6Ion8w1-I',
    appId: '1:521484955833:web:18785ff70c39af86a56b68',
    messagingSenderId: '521484955833',
    projectId: 'winggle-ac8d7',
    authDomain: 'winggle-ac8d7.firebaseapp.com',
    storageBucket: 'winggle-ac8d7.firebasestorage.app',
    measurementId: 'G-XKLQGF61R4',
  );

}